name: Verify presence of version bumps

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jsvd/logstash-plugin-actions@master
    - uses: actions/github-script@0.4.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'This Pull Request doesn\'t bump the gemspec version and CHANGELOG.md, making it more difficult to quickly publish this change.'
          })
