name: Verify presence of version bumps

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jsvd/logstash-plugin-actions@master
